-include config.out

SHELL=bash

Q ?= @
S ?= -s

.PHONY: all
all: start

#GCC vars
ifeq "$(cfg_gcc)" "y"
CC=$(cfg_usr_dir)/bin/gcc
CXX=$(cfg_usr_dir)/bin/g++
else
ifeq "$(origin CC)" "default"
CC=gcc 
CXX=g++
endif
endif

ifndef NO_CCACHE
CCACHE?=	$(firstword $(shell type -p ccache))
CC:=		"$(CCACHE) $(CC)"
CXX:=		"$(CCACHE) $(CXX)"
endif

CCOPTS    =  CC=${CC} CXX=${CXX}
MAKEOPTS  = -j20 ${CCOPTS}

##  Generate a valid configuration.
mk_dir := $(afterburn_dir)/Mk
include $(mk_dir)/Makefile.cml

##  Only include the remaining build logic if we have a valid configuration.
ifeq ($(cfg_cml),y)
include $(mk_dir)/Makefile.world
endif

##  By default, print the README.txt.
.PHONY: help start
help:
	@more $(afterburn_dir)/README.txt
	@touch Makefile.help
##  If necessary, generate a Makefile in the build directory, so that
##  the user only needs to execute 'make'.
ifeq ($(wildcard Makefile),)
start: Makefile
Makefile:
	@echo "include $(afterburn_dir)/Makefile" > Makefile
	@cp  $(afterburn_dir)/configs/sample-config.out config.out
	@echo "Your settings are now cached in Makefile"
else
ifeq ($(wildcard Makefile.help),)
start: help
else
start: world
endif
endif

