#!/usr/bin/env python

import sys

dquote = 0
squote = 0
escape = 0

while 1:
	c = sys.stdin.read(1)
	if c == "":
		break

	if c == '"' and not escape:
		dquote = not dquote
	if c == "'":
		squote = not squote
	if c == '\n':
		squote = dquote = 0
		escape = 0
	if c == ';' and not dquote and not squote:
		c = '\n'

	if c == '\\' and not escape:
		escape = 1
	else:
		escape = 0
	sys.stdout.write(c)

