
Q ?= @

.PHONY: all
all: start

clean: clean-apps

##  Our current directory.
mk_dir := $(drivers_dir)/Mk

##  Include rules for generating a valid configuration.
include $(mk_dir)/Makefile.cml
##  If a configuration already exists, include it.
-include config.out

##  Only include the remaining build logic if we have a valid configuration.
ifeq ($(cfg_cml),y)
cfg_pistachio_dir	:= $(subst ",,$(cfg_pistachio_dir))
cfg_marzipan_dir	:= $(subst ",,$(cfg_marzipan_dir))
cfg_install_dir		:= $(subst ",,$(cfg_install_dir))

include $(mk_dir)/Makefile.apps
endif

.PHONY: help start
help:
	@echo "No help yet ..."

##  If necessary, generate a Makefile in the build directory, so that the
##  user only needs to execute 'make'.
ifeq ($(wildcard Makefile),)
start: Makefile
Makefile:
	@echo "include $(drivers_dir)/Makefile" > Makefile
	@echo
	@echo "Your settings are now cached in $(CURDIR)/Makefile"
else
start: build-apps 
endif

