######################################################################
##                
## Copyright (C) 2003-2010,  Karlsruhe University
##                
## File path:     Mk/Makefile.top
## Description:   
##                
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions
## are met:
## 1. Redistributions of source code must retain the above copyright
##    notice, this list of conditions and the following disclaimer.
## 2. Redistributions in binary form must reproduce the above copyright
##    notice, this list of conditions and the following disclaimer in the
##    documentation and/or other materials provided with the distribution.
## 
## THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
## ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
## IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
## ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
## FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
## DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
## OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
## HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
## LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
## OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
## SUCH DAMAGE.
##                
## $Id$
##                
######################################################################

Q ?= @

.PHONY: all
all: start

clean: clean-apps

##  Our current directory.
mk_dir := $(drivers_dir)/Mk

##  Include rules for generating a valid configuration.
include $(mk_dir)/Makefile.cml
##  If a configuration already exists, include it.
-include config.out

##  Only include the remaining build logic if we have a valid configuration.
ifeq ($(cfg_cml),y)
cfg_pistachio_dir	:= $(subst ",,$(cfg_pistachio_dir))
cfg_marzipan_dir	:= $(subst ",,$(cfg_marzipan_dir))
cfg_install_dir		:= $(subst ",,$(cfg_install_dir))

include $(mk_dir)/Makefile.apps
endif

.PHONY: help start
help:
	@echo "No help yet ..."

##  If necessary, generate a Makefile in the build directory, so that the
##  user only needs to execute 'make'.
ifeq ($(wildcard Makefile),)
start: Makefile
Makefile:
	@echo "include $(drivers_dir)/Makefile" > Makefile
	@echo
	@echo "Your settings are now cached in $(CURDIR)/Makefile"
else
start: build-apps 
endif

